name: Run JavaScript Files with Playwright

on:
  schedule:
    - cron: '0 16 * * 0-5'
  workflow_dispatch:

env:
  IS_GITHUB_ACTION: ${{ secrets.IS_GITHUB_ACTION }}
  IS_BOOKING_DEBUG: ${{ secrets.IS_BOOKING_DEBUG }}
  LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
  BOOKING_PAGE_URL: ${{ secrets.BOOKING_PAGE_URL }}
  MSFT_EMAIL: ${{ secrets.MSFT_EMAIL }}
  MSFT_PWD: ${{ secrets.MSFT_PWD }}
  STORAGESTATE_FP: ${{ secrets.STORAGESTATE_FP }}
  BOOKING_DATE: ${{ secrets.BOOKING_DATE }}
  BOOKING_TIME_START: ${{ secrets.BOOKING_TIME_START }}
  BOOKING_TIME_END: ${{ secrets.BOOKING_TIME_END }}
  BOOKING_FACILITY: ${{ secrets.BOOKING_FACILITY }}
  BOOKING_PURPOSE: ${{ secrets.BOOKING_PURPOSE }}
  BOOKING_COBOOKER: ${{ secrets.BOOKING_COBOOKER }}

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install chromium

    - name: Install system dependencies for Playwright
      run: npx playwright install-deps chromium

    - name: Create .env with Github Secrets and run script
      run: |
        touch .env
        echo IS_GITHUB_ACTION=$IS_GITHUB_ACTION >> .env
        echo IS_BOOKING_DEBUG=$IS_BOOKING_DEBUG >> .env
        echo LOG_LEVEL=$LOG_LEVEL >> .env
        echo BOOKING_PAGE_URL=$BOOKING_PAGE_URL >> .env
        echo MSFT_EMAIL=$MSFT_EMAIL >> .env
        echo MSFT_PWD=$MSFT_PWD >> .env
        echo STORAGESTATE_FP=$STORAGESTATE_FP >> .env
        echo BOOKING_DATE=$BOOKING_DATE >> .env
        echo BOOKING_TIME_START=$BOOKING_TIME_START >> .env
        echo BOOKING_TIME_END=$BOOKING_TIME_END >> .env
        echo BOOKING_FACILITY=$BOOKING_FACILITY >> .env
        echo BOOKING_PURPOSE=$BOOKING_PURPOSE >> .env
        echo BOOKING_COBOOKER=$BOOKING_COBOOKER >> .env

    - name: Run the main script
      run: node --env-file=.env main.js
